// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeokjmznwecazievenzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Implb2tqbXpud2VjYXppZXZlbnp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzU0NTMsImV4cCI6MjA3MjgxMTQ1M30.NsZpXG2XODd-CKEFHjdEDCa4WsLA8c23zNXA5660bqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});